-- MySQL Script generated by MySQL Workbench
-- Mon Nov 19 13:07:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `AlphaCab`.`user`
-- -----------------------------------------------------
CREATE TABLE users(
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  usertype VARCHAR(255) NOT NULL,
  first_name VARCHAR(45) NOT NULL,
  Last_name VARCHAR(45) NOT NULL,
  PRIMARY KEY (id)
);


-- -----------------------------------------------------
-- Table `AlphaCab`.`customer`
-- -----------------------------------------------------
CREATE TABLE customer (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
  address VARCHAR(60) NOT NULL,
  user_id INT NOT NULL,
  PRIMARY KEY (id),
    FOREIGN KEY (user_id)
    REFERENCES users(id)
  );


-- -----------------------------------------------------
-- Table `AlphaCab`.`driver`
-- -----------------------------------------------------
CREATE TABLE driver (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
  registration VARCHAR(10) NOT NULL,
  user_id INT NOT NULL,
  PRIMARY KEY (id),
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    );


-- -----------------------------------------------------
-- Table `AlphaCab`.`journey`
-- -----------------------------------------------------
CREATE TABLE journey (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
  customer_id INT NOT NULL,
  start VARCHAR(60) NOT NULL,
  destination VARCHAR(60) NOT NULL,
  distance DOUBLE NOT NULL DEFAULT 1,
  date DATE NOT NULL,
  time TIME NOT NULL,
  fee INT NOT NULL,
  driver_id INT NOT NULL,
  status INT NOT NULL,
  PRIMARY KEY (id),
    FOREIGN KEY (customer_id)
    REFERENCES customer (id),
    FOREIGN KEY (driver_id)
    REFERENCES driver (id)
  );


-- -----------------------------------------------------
-- Table `AlphaCab`.`admin`
-- -----------------------------------------------------
CREATE TABLE admin (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
  user_id INT NOT NULL,
  PRIMARY KEY (id),
    FOREIGN KEY (user_id)
    REFERENCES users(id)
  );

  -- -----------------------------------------------------
  -- Table `AlphaCab`.`fee_amount`
  -- -----------------------------------------------------
  CREATE TABLE fee_amount (
    id INT NOT NULL GENERATED ALWAYS AS IDENTITY
          (START WITH 1, INCREMENT BY 1),
    vat DOUBLE NOT NULL,
    price_per_mile INT NOT NULL,
    short_distance DOUBLE NOT NULL,
    extra_charge INT NOT NULL,
    PRIMARY KEY (id)
    );

-- -----------------------------------------------------
-- Data for table `AlphaCab`.`user`
-- -----------------------------------------------------
INSERT INTO users(username, password, usertype, first_name, Last_name) VALUES
('smithe@mail.com', 'password', 'CUSTOMER', 'Eva', 'Smith'),
('mantonr@mail.com', 'password', 'CUSTOMER', 'Rob', 'Manton'),
('currieb@mail.com', 'password', 'CUSTOMER', 'Bob', 'Currie'),
('hunterj@mail.com', 'password', 'CUSTOMER', 'Jim', 'Hunter'),
('johnsonp@mail.com', 'password', 'CUSTOMER', 'Phil', 'Johnson'),
('soylers@mail.com', 'password', 'CUSTOMER', 'Saim', 'Soyler'),
('hikmetg@mail.com', 'password', 'CUSTOMER', 'Gul', 'Hikmet'),
('smithj@mail.com', 'password', 'DRIVER', 'John', 'Smith'),
('aydinm@mail.com', 'password', 'DRIVER', 'Mehmet', 'Aydin'),
('johnsonm@mail.com', 'password', 'DRIVER', 'Mark', 'Johnson'),
('admin@mail.com', 'admin', 'ADMIN', 'Admin', 'User');


-- -----------------------------------------------------
-- Data for table `AlphaCab`.`customer`
-- -----------------------------------------------------
INSERT INTO customer (address, user_id) VALUES
('129 Station Rd, London, N3 2AS', 1),
('23 Bow Lane, London, N3', 2),
('54 Teignmouth Rd, London, NW2', 3),
('765 High Road, London, N12', 4),
('75 Squires Lane, London, N3', 5),
('2 Rosemary Ave, London, N3', 6),
('31 Clifton Rd, London, N3 2SG', 7);


-- -----------------------------------------------------
-- Data for table `AlphaCab`.`driver`
-- -----------------------------------------------------
INSERT INTO driver (registration, user_id) VALUES
('AK52VZV', 8),
('BN60WKA', 9),
('R34AKP', 10);

-- -----------------------------------------------------
-- Data for table `AlphaCab`.`journey`
-- -----------------------------------------------------

INSERT INTO journey (customer_id, start, destination, distance, date, time, fee, driver_id, status) VALUES
(1, 'Finchley, London', 'King''s Cross Station, London', 5, '2015-10-14', '09:30:00', 500, 2, 0),
(7, 'Oriental Rd, Woking', 'Heathrow Terminal 3, London', 20, '2015-10-14', '12:00:00', 2000, 2, 0),
(7, 'Barnet Hospital, Wellhouse Ln, Barnet EN5 3DJ', '120 Green Lanes, London, N13', 7, '2015-10-15', '06:00:00', 700, 1, 0),
(7, 'High St N, London N14 5BH', '131 Stoke Newington High Road, London, N12', 8, '2015-10-15', '12:00:00', 800, 1, 0),
(1, 'Bletchley Park Milton Keynes MK3 6EB', 'Luton Airport, Luton', 30, '2015-10-22', '10:00:00', 3000, 3, 0);


-- -----------------------------------------------------
-- Data for table `AlphaCab`.`admin`
-- -----------------------------------------------------

INSERT INTO admin (user_id) VALUES (11);

-- -----------------------------------------------------
-- Data for table `AlphaCab`.`fee_amount`
-- -----------------------------------------------------

INSERT INTO fee_amount (vat, price_per_mile, short_distance, extra_charge) VALUES
(0.2, 250, 2, 200);
